### ISSUE TITLE
📋 [PUML TASK] - Update PUML Requirements Diagram Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-puml#10]
### Parent Feature

#7

### Task Description

As an AaC Developer, I want to update the `gen-puml` `puml-requirement` diagram templates, so that I have a correct and consistent diagram returned to end users.

### Acceptance Criteria

- [x] Requirement diagram template is updated to use AaC `generate` helper functions as necessary.
- [x] Requirement diagram template is updated to use the new definition object.
- [x] Requirement diagram template is updated to meet diagram needs.
