### ISSUE TITLE
📋 [PUML TASK] - Update Workflows in PUML Repository

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-puml#28]
### Parent Feature

#27

### Task Description

As an AaC Developer, I want to pull the latest workflows for the PUML Repository, so that I have the latest supported pipelines.

### Acceptance Criteria

- [x] Pull the updated python-build-and-lint.yml workflow
- [x] Pull the updated python-cross-platform-support.yml workflow
- [x] Pull the updated python-deploy-artifacts.yml workflow
- [x] Pull the updated python-test-python-version.yml workflow
- [x] Pull the updated codeql-analysis.yml workflow
- [x] Pull the updated deploy-pages.yml workflow
- [x] Pull the updated main-branch.yml workflow
- [x] Pull the updated pull-requests.yml workflow
- [x] Pull the updated dependabot.yml configuration.
- [x] Remove legacy issue templates
- [x] Remove legacy PR template

**Comment by lizzcondrey** [comment]
@bunchw, I didn't come back and look over this issue like I should have for confirming everything was taken care of. Still need to remove the legacy templates from PUML repo.
