### ISSUE TITLE
📋 [PUML TASK] - Update PUML Plugin to Use New API

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-puml#4]
### Parent Feature

#761 

### Task Description

As an AaC Developer, I want to update the `gen-puml` plugin to use the new API, so that I provide an updated version of the capability. 

### Acceptance Criteria

- [x] Utilize the `gen-plugin` command from AaC to create all boilerplate plugin files.
- [x] `gen-puml` init is updated to use the new API.
- [ ] `gen-puml` implementation is updated to use the new API. 
- [ ] `gen-puml` unit tests are updated to use the new API.
