### ISSUE TITLE
📋 [TASK] - Pip Upgrade Steps

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-puml#40]
### Parent Feature

N/A

### Task Description

As an AaC Developer, I need to update my gitpod.yml file to include a `pip install --upgrade pip` step, so that my dev environment is up to date.

### Acceptance Criteria

- [x] Confirm all repositories have:
  - [x] gitpod.yml file has a step before package install for upgrading pip.
  - [x] gitpod.yml file package install step is consistently set for .[all] so that all dependencies are properly installed

**Comment by jasoncbryant** [comment]
python -m pip install --upgrade pip
      pip install -e .[all]
Confirmed in .gitpod.yml
