### ISSUE TITLE
📋 [PUML TASK] - Update PUML Component Diagram Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-puml#8]
### Parent Feature

#7

### Task Description

As an AaC Developer, I want to update the `gen-puml` `puml-component` diagram templates, so that I have a correct and consistent diagram returned to end users.

### Acceptance Criteria

- [ ] Component diagram template is updated to use AaC `generate` helper functions as necessary.
- [ ] Component diagram template is updated to use the new definition object.
- [ ] Component diagram template is updated to meet diagram needs. 
- [ ] Component diagram unit tests are updated to evaluate output.
