### ISSUE TITLE
📋 [PUML TASK] - Update PUML Sequence Diagram Template

### ISSUE THREAD

**Issue by lizzcondrey** [DevOps-MBSE/aac-puml#9]
### Parent Feature

#7

### Task Description

As an AaC Developer, I want to update the `gen-puml` `puml-sequence` diagram templates, so that I have a correct and consistent diagram returned to end users.

### Acceptance Criteria

- [x] Sequence diagram template is updated to use AaC `generate` helper functions as necessary.
- [x] Sequence diagram template is updated to use the new definition object.
- [x] Sequence diagram template is updated to meet diagram needs. 
- [x] Sequence diagram unit tests are updated to evaluate output.
